beatmasterRS/skin.arctic.zephyr.mod

- language/Spanish/strings.po
> Spanisch language file

- language/Spanish/strings.po
> Update spanish translation

- 1080i/View_510_Minimal.xml
- 1080i/View_520_Minimal.xml
> Fix duration time for Big Icons-Flix view mode 

- 1080i/Custom_Ratings.xml
When I touched the flags I forget this one...
Im not sure how test/enable tomatoes, I could not put to work on my machine 🤷 
But I hope it is right! The settings is there :D
> [Custom_Rating] Put tomatoes settings back

- 1080i/Includes_Home.xml
The weather was using `2` for spacing and now will be `3`, but I dont think the diference is noticeable :) 
I did my testes here but I appreciate more tests, to make sure is fine
> [Home] Reduce replicated code, extending focused widget

- 1080i/View_53_Poster.xml
https://github.com/semool/skin.arctic.zephyr.mod/commit/25c469ed90d5bf7e7bb412d010529dff06b1ae9f
> Code Cleanup for view53 Alternative Overlays

- 1080i/Custom_1297_Blur.xml
- 1080i/Includes.xml
I dont think that is the ideal setting. But I'd like to remove the background (and the blur) **but still having the netflix fanart**... 
The clever and easy way I could think for now is to allow set the opacity level in blur settings to 0
> [Background] Add setting to set blur opacity level 0

- 1080i/Includes.xml
This closes #134 
Im not sure if it's right, seems too easy to be right hahahha Im kindly asking review 
**before**
**after**
> [Expression] Match new content for Home.xml

- 1080i/Includes.xml
- changed control type to image,  as there is no reason to use multiimage. 
- better control by constant "HomeTimePerImage" about time per image, when extrafanart is used.
> [Background Code] changed control type from multiimage to image

- extras/playlists/InProgressTvShows.xsp
- shortcuts/overrides.xml
This xsp represent a real InProgressTvShows list
> add InProgressTvShows.xsp

- language/Finnish/strings.po
> Finnish translation

- language/French/strings.po
Full Update French Language from English Language
> Update French Language

- language/French/strings.po
French translate updated + minor adjustment
> French translate updated + minor adjustment

- language/French/strings.po
Sorry, must be good this time :)
> french translate minor error + missing

- language/French/strings.po
> french translate

- 1080i/DialogSlider.xml
Minor change to fix separator width to match slider.
> Fix Audio Offset separator

- language/French/strings.po
> French translate minor adjustment

- 1080i/Custom_SetViewtype.xml
So let's take it step by step :D
Probably the only part I can save from https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/250
> [Fix] - Label hard coded

- 1080i/Custom_SetViewtype.xml
- 1080i/View_520_Minimal.xml
- 1080i/View_522_Minimal_V2_Episodes.xml
- 1080i/View_55_Wall.xml
- language/English/strings.po
- language/Finnish/strings.po
- language/French/strings.po
- language/German/strings.po
- language/Hungarian/strings.po
- language/Italian/strings.po
- language/Korean/strings.po
- language/Spanish/strings.po
no initiative this time. Only what you wanted :D 
changed : 
Big Icons-Flix => Poster Flix
Big Icons-Flix v2 => Poster Flix v2
Wall Small => Poster Wall Small
Big icons => Big Poster
news : 
Poster Wall (replace "Icons" 536)
Fanart Flix
Fanart Flix v2
> [Label ViewType] Improvement and consistancy

- language/French/strings.po
> [Localization] - French translate - minor adjustment

- 1080i/Includes.xml
- 1080i/Includes_Defs.xml
- 1080i/Includes_DialogVideoInfo.xml
- 1080i/Includes_Labels.xml
<param name="onclick1" value="$VAR[value]"       
$VAR[value] must be diferente if movie or TV Show
eg : see `` and `` in "Includes_DialogVideoInfo.xml"
PS : I m not very good with Github. It is why I make a new branch :S
> [DialogVideoInfo Studios] fix 2

- 1080i/Includes.xml
https://www.reddit.com/r/Addons4Kodi/comments/ntigl0/artwork_beef_for_kodi_matrix_work_in_progress/
https://github.com/henryjfry/fryhenryj/blob/master/script.artwork.beef-matrix.zip?raw=true
https://github.com/henryjfry/fryhenryj/blob/master/script.common.plugin.cache-2.6.1.1-matrix.zip?raw=true
> [Artwork Beef] readd support for artwork.beef

- 1080i/Includes_Defs.xml
After comment the line 90 in Includes_Defs.xml
this error that appear often in the LOG Kodi  :
`ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting noop`
Disapear and I see nothing break in skin AZR ...
> [Fix]  ERROR "GetDirectory - Error getting noop" in LOG

- shortcuts/template.xml
https://forum.kodi.tv/showthread.php?tid=337862&pid=3042501#pid3042501
> [Fix] Weather Widget not display at startup

- 1080i/service-LibreELEC-Settings-mainWindow.xml
Before : 
- logo is missing
- some *.png are not show
- focus not visible
After :
> [LibreElec] Fix Improve LibreElecSettings MainWindows

- 1080i/service-LibreELEC-Settings-mainWindow.xml
Sorry I have change only one things. 
The red font is absolutely not possible for my eyes o_O
Other works is needed to fit to AZR completely...
But it is much better than before :D
> [LibreElec] design fit to  AZR

- 1080i/service-CoreELEC-Settings-mainWindow.xml
- 1080i/service-LibreELEC-Settings-mainWindow.xml
- replace "red" font by "PanelWhite30" like LibreElec
- fix code deprecated line 1088 :)
If you can test please. 
I have no CoreElec system in my side ...
> [CoreElec] Minor adjustement + fix code deprecated

- 1080i/service-CoreELEC-Settings-mainWindow.xml
> little search and replace fix

- 1080i/SkinSettings.xml
duplicate option in SkinSettings.xml
line 451
line 2586
> [Cleanup] duplicate option

- 1080i/MusicVisualisation.xml
see : https://github.com/beatmasterRS/skin.arctic.zephyr.mod/issues/362
> [Fix] fallback image OSD music or Slideshow

- 1080i/Includes.xml
Add the the possibility to display "fanart fallback"
before :  
AS3 => fanart => menu background => black screen
after :   
AS3 => fanart => fanart fallback => menu background => black screen
> [Show now playing] improvement

- 1080i/Includes_Labels.xml
- 1080i/Includes_NowPlaying.xml
- 1080i/SkinSettings.xml
- language/resource.language.en_gb/strings.po
> [NowPlaying] option to enable tracklist instead artist/albuminfo for music

- .github/workflows/sync-addon-metadata-translations.yml
- language/resource.language.it_it/strings.po
More fixes.
I think I accidentally converted it to Unix EOL.
Sorry :)
> Workflow and errors

- language/resource.language.es_es/strings.po
- language/resource.language.fi_fi/strings.po
- language/resource.language.ko_kr/strings.po
Some more language file fixes.
> [Strings] Fixes for language files

- 1080i/Includes_Home.xml
- 1080i/SkinSettings.xml
Hide completely menu for Vertical like Modern when slide out
> [Home Vertical] Hide completely menu when slide out

- 1080i/Defaults.xml
continuation and end : https://github.com/beatmasterRS/skin.arctic.zephyr.mod/issues/442
This PR is needed too. thanks :)
> [Textures] fixed filename and path - 2

- 1080i/Includes.xml
- 1080i/MyVideoNav.xml
- 1080i/View_521_Minimal_V2.xml
> [View 521] added alternative layout setting

- 1080i/Includes_Furniture.xml
- 1080i/MyVideoNav.xml
- 1080i/MyWeather.xml
- 1080i/View_510_Minimal.xml
- 1080i/View_520_Minimal.xml
- 1080i/View_521_Minimal_V2.xml
- 1080i/View_522_Minimal_V2_Episodes.xml
- 1080i/View_523_Minimal_V2_Music.xml
- 1080i/View_524_Minimal_V2_Seasons.xml
- 1080i/View_527_List_V2.xml
@Nanomani i have added slide animations to Includes_Furniture.xml, to adjust the bottom position in some views, that has bothered me a lot. With that, i can live :)
Sorry for the trouble :I
> [Jumpbar Views 510 521 522 523 527] added jumpbar to views

- 1080i/Includes_DialogVideoInfo.xml
duplicate code line 1038 and line 1064 in Includes_DialogVideoInfo.xml
> [Code] cleanup duplicate code

- 1080i/SkinSettings.xml
> [Code] fixed visible condition bracket

- 1080i/Includes_Furniture.xml
display flag 3D if ".3D" in filename
> [Flags] improvement display flag 3D if ".3D" in filename

- 1080i/Includes.xml
- 1080i/Includes_Home.xml
…ground is enabled, but no visualisation is chosen
> [Visualisation] fixed possible issue, when visualisation in the background is enabled, but no visualisation is set

- 1080i/Includes_Labels.xml
- 1080i/Includes_NowPlaying.xml
- 1080i/Includes_OSD.xml
- 1080i/SkinSettings.xml
- language/resource.language.en_gb/strings.po
> [NowPlaying Controls] added fullscreen button, added always visible option

- shortcuts/overrides.xml
before this PR : 
open dialog "favourites" onclick item "more" with widget "Favourites"
after this PR : 
open new windows "favouritesbrowser" onclick item "more" with widget "Favourites"
> NEXUS - [Favourites] added new favourites on widget item "more"

- 1080i/SettingsCategory.xml
> [SettingsCategory] improvements

- 1080i/Includes_DialogMusicInfo.xml
big one monster catch :D
before : 
after :
> [DialogMusicInfo] typo fix

- 1080i/Includes.xml
- 1080i/Includes_DialogMusicInfo.xml
> [DialogMusicInfo] improvement - extended Artist Fanart for Item Album

- 1080i/Includes_Labels.xml
- 1080i/View_50_List.xml
> [Views FileSize] added filesize to list views with sorted "File"

- 1080i/Includes_Custom_Items.xml
- 1080i/Includes_Labels.xml
- language/resource.language.en_gb/strings.po
> [Color Presets] added yellow color preset

- 1080i/Includes_Home.xml
> switch font for next recording window
