beatmasterRS/skin.arctic.zephyr.mod

1080i/Custom_VideoSetting.xml, 1080i/DialogSeekBar.xml, 1080i/SkinSettings.xml, 1080i/VideoOSD.xml
This is my first time working for Kodi... So, Im not sure about the pull request, I just did my best here.
**My problem**
Im running Kodi for windows in my TV.   
Kodi 19 has HDR and automatic turn Windows' HDR when need.  
Im using `Show detailed info when video is paused`   
_The problem starts here_  
When you're playing HDR and the OSD appears and contains an image **the image _(in that case the poster)_ looks extreme ugly**, at least in my setup it does...
**What I think**
Of course I can disable the `detailed info when video is paused` but it is nice to see some info there (like title, episode, etc), I kinda like it.  
I just don't like the way that the image is today, maybe it changes in future, maybe the problem occurs only for me, I don't know. 
I thought about remove the image …
=> [Feature] Option to disable poster from detailed info osd (only matrix osd)

1080i/DialogSeekBar.xml, 1080i/Includes_Defs.xml, 1080i/Includes_OSD.xml, 1080i/VideoOSD.xml
After my last changes, I've notice that without the poster we can use more space for the movie title/episode. 
I did tests with movie and tvshow and I figured out some values that looks good to me.
I just dont know about PVR content, I never used, I know nothing... 
I also improve the conditionals to now take into account the numeric rating as well (stars rating uses more space) 
And I kept the same width for `flagiconsosd` and `flagiconsosdnoicons`. Could be different since `flagiconsosdnoicons` consumes less space, but for now its fine. 
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Ps. For episodes there's an auto scroll effect, the rest of `Adventure Time` title will appears in that scroll... Different of the Movie that only has `...`
=> Improve OSD title width

1080i/Custom_Ratings.xml, 1080i/Custom_VideoSetting.xml, 1080i/Includes_Defs.xml, 1080i/Includes_Furniture.xml, 1080i/MyVideoNav.xml, 1080i/SkinSettings.xml, language/English/strings.po, language/German/strings.po, language/Korean/strings.po, language/Spanish/strings.po
What I did:
- Created a settings in `forniture/media flags` to select which flags you want to see ([example](https://user-images.githubusercontent.com/15933/106672612-3e5b1600-65a8-11eb-9ae3-3e54387981e2.png))
- Changed the forniture flags icons (color and not) to follow those settings ([example](https://user-images.githubusercontent.com/15933/106672797-9560eb00-65a8-11eb-88f4-4c650c03ace7.png))
- Fixed a bug (I think so) that removes the `duration` when `media flags` was disable in some views (like icons and big icons). Now the `duration` will always appear in those views. ([example](https://user-images.githubusercontent.com/15933/106673054-f7215500-65a8-11eb-8b7a-deedc15e488a.png))
What are missing:
- **String.po** I have create some strings and I dont know the best way to add it to …
=> Select custom media flags

1080i/Custom_SetViewtype.xml, 1080i/View_510_Minimal.xml
I would like to enable the 510 "Big-flix Icons" for seasons because Im using Poster for seasons and 520 only show Fanart (landscape or  thumbs).
I've tested and I did not see problems on that.  
Should we enable even for episodes? 
**Big-Flix (the View_510)**
**Big-Flix Episodes (the view 520)**
=> [ViewType] Enable View_510 for Seasons and Episodes

1080i/Includes_Furniture.xml, 1080i/Includes_Labels.xml, 1080i/MyVideoNav.xml, 1080i/View_510_Minimal.xml, 1080i/View_520_Minimal.xml, language/English/strings.po, language/German/strings.po, language/Korean/strings.po, language/Spanish/strings.po, shortcuts/overrides.xml
- Small changes on the `scrollbar_hor` width, notice by the grid that looks more centralized with `1740`
- But why not use 100% of the grid?
- When scrolling through Big-Flix, since we have a bigger highlight item, we should move down the scrollbar, I figured out `162` looks good
- Added a new option (only for 510 and 520) to hide the scrollbar during the scrolling event... The scroll still there but will not appear during the "auto scroll", you know?
- I notice one duplicated language string `Wrap list` and I used the ID for this options. Is that fine?
What you think?
Im not sure if we should change the default behaviour (to dont show the scroll when scrolling) or just add a new option... But that is it for now :D 
**The old position**
**The new position**
=> [ViewType] Option to hide scrollbar when scrolling

1080i/Includes_Home.xml, 1080i/Includes_Labels.xml
I notice some home widgets are not formatted to "new time"
Because those widgets are using `$PARAM[id]` to determine `Container.ListItem`, I could only duplicate the code...
I was not able to use the the same variable `LabelDurationTimeCheck` from "Includes_Labels.xml"...
Maybe you have some ideia to improve that avoiding duplicate code
**New Time format disabled**
**New Time format enable**
=> [Widgets] Format duration time

1080i/Includes.xml
Recently I got some subs in x265 that are using [opus](https://en.wikipedia.org/wiki/Opus_(audio_format)) codec and the theme was showing just `???` for that.
I dont know how usually that codec are (maybe is rare) but I dont like to see `???`...
I add 3 files to `Texture.xbt` (using windows texture tool)
`flags/audio/opus.png` 
`flags3/audio/opus.png`
`flags/color/audio/opus.png`
**The result**
=> [AudioCodec] Add opus flag

1080i/Includes.xml, 1080i/Includes_Furniture.xml, 1080i/Includes_OSD.xml
I thought I had test this case, but looks like not...
The thing is, we can not test the string `hdr` without the comma as limiter (before and after), otherwise we will always have missmatching, like contains `.hdr` or `hdr` will both be true for `.hdr10` and `.hdr10plus`, the same for `.hdr10` to `.hdr10plus` etc... 
Lets be more restrictive and set only the comma as limiter (at least for HDR)... what do you think? Is it fine?
=> [Flags] Fix HDR condition

1080i/Includes.xml, 1080i/Includes_Furniture.xml, 1080i/Includes_OSD.xml
I think we can use expressions to reduce some duplicated code.
Im using the same conditional for ListItem + VideoPlayer, by my tests its fine. What do you think? 
Tell me if it is wrong 
Are we using the HUB thing? I dont know what is or how can I see... but there are some pieces of code that mention the `Container(9500)` and I assume that is for the Hub, I dont know how test it... looks like there are some outdated code there...
=> Use expression for audiocodec and hdr detection

1080i/Custom_Ratings.xml, 1080i/Includes.xml, 1080i/Includes_Furniture.xml
I also notice two things:
- is not showing in home widgets
- the 5 stars (without numeric) for tvshow/season are not working (but the numeric is)
I will investigate this better but in another PR
I think we should use more the `<expression>` what do you think? Is it fine or should I stop to use?
=> [Flags] Disable the next aired information

1080i/Includes_Furniture.xml, 1080i/Includes_Home.xml
I said in the forum but I went a bit deeper and now I got what was the commit about.
We need to move a little bit upper the clearlogo when is Vertical Widgets... fine, but we dont need it to vertical netflix... So I change the conditional.
**Before**
**After**
And still the same position for vertical widgets
=> [Furniture] Fix clearlogo position for vertical netflix widget

1080i/Includes_Images.xml, 1080i/Includes_Labels.xml, 1080i/SkinSettings.xml
This PR closes #106 and This PR depends on #109 
I think those settings is good because if you're using the list view you may see a lot of "dots" for unwatched content, like this:
I added to `Furniture` the options to select the flags: 
The state of the options If `Indicators` is disable:
And the result could be (depends on the settings)
=> [SkinSettings] Choose indicators settings

1080i/Custom_SetMusicViewtype.xml, 1080i/Custom_SetViewtype.xml, 1080i/Includes_Labels.xml, 1080i/View_500_Thumbnails.xml
An other one from https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/250
In "Custom_SetViewtype.xml" you use code label "31264" for layout "500"
But not in "View_500_Thumbnails.xml" where you use kodi code label "21371"
=> [Fix] - Label code kodi. Must be code label AZR

1080i/Custom_DialogSettings.xml
- showbutton.video.director
- showbutton.video.set
are unnecessary for TV Shows
=> [TV Show] disable some option in DialogSetting in DialogVideoInfo if TV Show

1080i/Custom_SetViewtype.xml
I often switch between "Poster Wall" and "Poster wall small"
this PR move "Poster wall small"  under "Poster Wall"  in list Viewtype .
If you are not agree so don't worry and please close this PR.
Thanks :)
=> [Viewtypelist] move "Poster wall small" under "Poster wall" in list Viewtype

1080i/Includes_Furniture.xml, 1080i/MyVideoNav.xml, 1080i/View_510_Minimal.xml, 1080i/View_520_Minimal.xml, 1080i/View_521_Minimal_V2.xml, 1080i/View_522_Minimal_V2_Episodes.xml, 1080i/View_523_Minimal_V2_Music.xml, 1080i/View_524_Minimal_V2_Seasons.xml
Hello, its been a while since my last contribution but Im still following (and using daily) the theme. I've notice the new Flix views and its amazing! 
Just one thing I did in the past (#67) about the Flix v1, its the ability to hide the scrollbars animations when it's scrolling. The scroll still there but will need to be focused to be visible. 
Since we already have the option `ShowScrollbar510` and I notice the new views use the `scrollbar_hor` as well, I think I can reuse it.
=> [Scrollbar] Option to hide scrollbar for more views (Flix v2)

1080i/Includes.xml
I was trying the home "clean & minimal" so I disabled the "blur on home"
But Im still using the Flix views, then I notice the fullsize fanart stopped to work
The fix is just to remove the `BlurOnHome` conditional for that, worked here but Im not sure if that's all (I hope so)
=> [Bugfix] Netflix fullsize fanart

1080i/Includes_Furniture.xml, 1080i/View_521_Minimal_V2.xml
When you're on Modern Widgets and have the clearlogo enabled, you see missaligned (compared to the views)
This MR fixed it
Would be nice to know better WHY this happens instead of just conditionally fix the position... but... that's what I got xD
=> [Clearlogo] Fix clearlogo position top position for Modern Widgets

1080i/SettingsProfile.xml, 1080i/SettingsSystemInfo.xml
SettingsProfiles : line too wide
SettingsSystemInfo.xml : line missing
before : 
after :
=> minor adjustment

.github/workflows/sync-addon-metadata-translations.yml, language/resource.language.it_it/strings.po
This will add a workflow to automatically sync `summary`, `description` and `disclaimer` between language files and addon.xml
It will run whenever either language files or addon.xml are changed, and will create PR's for the changes.
This will also fix a syntax error in `it_it` language file.
It's necessary to fix to add the skin for translation at Weblate.
=> Workflow and errors

1080i/SkinSettings.xml
hide settings not `<enable>` in all case for selected layout is more clean less confuse.
before : 
after : 
before : 
after :
=> [SkinSettings] improvement

1080i/DialogSeekBar.xml
fix this issue : https://github.com/beatmasterRS/skin.arctic.zephyr.mod/issues/499
works with all display mode "AZR, standard, On Side"
=> [Fix] fixed issue with OSD LiveTv double icon in some cases

1080i/Includes_Labels.xml, 1080i/View_54_Banner.xml
This allows flattened episode lists to be usable, otherwise there's no way to distinguish between same numbered episodes across different seasons.
=> Add season number to Wide episodes view

1080i/Includes.xml
settings "Extra fanart" works fine in view 523 artists but not with DBtype albums
- Before this fix Fanart don't slideshow for album focus
- After this works well if you have multi Fanart for the artist of the album focus
=> [Fix] Extra Fanart don't works in view flix albums

1080i/Includes_SubItems_Home.xml
"Widgets fade animation" disable have no effect for "system info" and "settings" Widget : 
Before : 
After :
=> [Fix] Widgets fade animation disable don't works for "system info" and "settings" widgets

1080i/Includes_Labels.xml
=> [Code] Fix unmatched parentheses

1080i/Includes_Labels.xml
(Re)loading the skin would throw an error into the log and any changes to the home menu layout would not be applied:
```
2023-06-10 13:17:29.190 T:408450   error <general>: unmatched parentheses in string.isempty(container(301).listitem.property(watchedepisodepercent)
```
This PR adds the missing parenthesis to `Includes_Labels.xml`.
=> Add missing close parenthesis to Includes_Labels.xml
